[2024-07-07T07:00:30.555+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: Final_exam.starting manual__2024-07-07T06:59:21.144047+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-07-07T07:04:49.254+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: Final_exam.starting manual__2024-07-07T06:59:21.144047+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
