[2024-07-07T08:15:05.903+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: Final_exam.starting manual__2024-07-07T08:11:03.930443+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
