[2024-07-07T07:07:11.525+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: Final_exam.starting manual__2024-07-07T14:06:36+07:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
